name: coverage

on:
  push:
    branches: ["master"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc \
          make \
          meson \
          ninja-build \
          libgit2-dev \
          libffi-dev \
          pkg-config \
          cmake \
          git \
          gcovr \
          bear

    - name: Generate compile_commands.json
      run: |
        bear -- make

    - name: Build and run unit tests
      run: make test && ./bin/test

    - name: Generate coverage report
      run: make coverage

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v7
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} 
      with:
        args: >
          -Dsonar.organization=under-tension
          -Dsonar.projectKey=under-tension_magma
          -Dsonar.cfamily.compile-commands=./compile_commands.json
          --define sonar.coverageReportPaths=./bin/coverage.xml